use std::sync::OnceLock;

//
// Build-time embedded documentation sources: a flat list of
// (relative_path, contents) pairs generated by service/build.rs from
// docs/src/**/*.md.
//
include!(concat!(env!("OUT_DIR"), "/embedded_docs.rs"));

//
// A single retrievable unit of documentation: one markdown section, keyed by
// its source page and heading trail. Chunking at the heading level keeps each
// unit topically coherent and small enough that a handful can be injected into
// a prompt without dominating the context window.
//

pub struct DocChunk {
    pub path: String,
    pub heading: String,
    pub body: String,
}

//
// Parse all embedded docs into heading-level chunks, once, on first use.
//

fn all_chunks() -> &'static Vec<DocChunk> {
    static CHUNKS: OnceLock<Vec<DocChunk>> = OnceLock::new();
    CHUNKS.get_or_init(|| {
        let mut chunks = Vec::new();
        for (path, content) in EMBEDDED_DOCS {
            chunk_page(path, content, &mut chunks);
        }
        chunks
    })
}

//
// Split one markdown page into chunks at ATX headings (lines beginning with
// `#`). Content before the first heading is attached to a synthetic chunk
// named after the page. Fenced code blocks are tracked so a `#` inside a code
// fence is not mistaken for a heading.
//

fn chunk_page(path: &str, content: &str, out: &mut Vec<DocChunk>) {
    let mut heading = page_title(path);
    let mut body = String::new();
    let mut in_fence = false;

    let flush = |heading: &str, body: &mut String, out: &mut Vec<DocChunk>| {
        if !body.trim().is_empty() {
            out.push(DocChunk {
                path: path.to_string(),
                heading: heading.to_string(),
                body: std::mem::take(body),
            });
        } else {
            body.clear();
        }
    };

    for line in content.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            in_fence = !in_fence;
        }

        if !in_fence && trimmed.starts_with('#') {
            flush(&heading, &mut body, out);
            heading = trimmed.trim_start_matches('#').trim().to_string();
            if heading.is_empty() {
                heading = page_title(path);
            }
        } else {
            body.push_str(line);
            body.push('\n');
        }
    }
    flush(&heading, &mut body, out);
}

//
// Derive a human-ish page title from a doc path, e.g.
// "usage/log-query.md" -> "log query".
//

fn page_title(path: &str) -> String {
    path.trim_end_matches(".md")
        .rsplit('/')
        .next()
        .unwrap_or(path)
        .replace(['-', '_'], " ")
}

//
// Tokenize into lowercase alphanumeric terms, dropping very short tokens and a
// small set of common stopwords that carry no retrieval signal.
//

fn tokenize(text: &str) -> Vec<String> {
    text.split(|c: char| !c.is_alphanumeric())
        .filter_map(|w| {
            let w = w.to_lowercase();
            if w.len() < 3 || STOPWORDS.contains(&w.as_str()) {
                None
            } else {
                Some(w)
            }
        })
        .collect()
}

const STOPWORDS: &[&str] = &[
    "the", "and", "for", "are", "how", "does", "did", "can", "you", "your", "with", "what", "when",
    "where", "why", "who", "that", "this", "from", "into", "was", "were", "will", "would",
    "should", "there", "here", "have", "has", "had", "not", "but", "all", "any", "get", "got",
    "use", "used", "using", "about", "which", "them", "they", "its",
];

//
// Score a chunk against the query terms. Heading matches are weighted more
// heavily than body matches, and the score is length-normalized so short,
// on-topic sections are not out-competed by long tangential ones.
//

fn score_chunk(chunk: &DocChunk, query_terms: &[String]) -> f32 {
    let heading = chunk.heading.to_lowercase();
    let body = chunk.body.to_lowercase();
    let body_len = (chunk.body.split_whitespace().count().max(1)) as f32;

    let mut score = 0.0f32;
    for term in query_terms {
        if heading.contains(term.as_str()) {
            score += 3.0;
        }
        let hits = body.matches(term.as_str()).count() as f32;
        if hits > 0.0 {
            //
            // Sub-linear term frequency (1 + ln tf) so repeated terms help but
            // with diminishing returns, then normalized by section length.
            //
            score += (1.0 + hits.ln()) / body_len.sqrt();
        }
    }
    score
}

//
// Tool-facing search: rank chunks against a free-text query and return a
// compact list of matches (page, heading, snippet) so the assistant can decide
// which pages to read in full.
//

pub fn search(query: &str, top_n: usize) -> String {
    let terms = tokenize(query);
    if terms.is_empty() {
        return "No usable search terms in the query.".to_string();
    }

    let mut scored: Vec<(f32, &DocChunk)> = all_chunks()
        .iter()
        .map(|chunk| (score_chunk(chunk, &terms), chunk))
        .filter(|(score, _)| *score > 0.0)
        .collect();
    scored.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));

    if scored.is_empty() {
        return format!(
            "No documentation sections matched \"{}\". Try different keywords, or read a page \
             from the table of contents with read_doc.",
            query
        );
    }

    let mut out = String::new();
    for (_, chunk) in scored.into_iter().take(top_n) {
        let snippet: String = chunk
            .body
            .split_whitespace()
            .take(28)
            .collect::<Vec<_>>()
            .join(" ");
        out.push_str(&format!(
            "- {} \u{2014} {}\n  {}\n",
            chunk.path.trim_end_matches(".md"),
            chunk.heading,
            snippet
        ));
    }
    out
}

//
// Tool-facing page read: return the full text of a documentation page by path,
// tolerant of a leading "./", a missing ".md", and case. Truncated to
// `max_chars` characters so a single read stays bounded.
//

pub fn read_page(path: &str, max_chars: usize) -> Option<String> {
    let want = path
        .trim()
        .trim_start_matches("./")
        .replace('\\', "/")
        .trim_end_matches(".md")
        .to_lowercase();

    EMBEDDED_DOCS.iter().find_map(|(p, content)| {
        if p.trim_end_matches(".md").eq_ignore_ascii_case(&want) {
            let truncated: String = content.chars().take(max_chars).collect();
            let note = if truncated.len() < content.len() {
                "\n\n[...page truncated...]"
            } else {
                ""
            };
            Some(format!("{}{}", truncated, note))
        } else {
            None
        }
    })
}
