use std::sync::OnceLock;

//
// Build-time embedded documentation sources: a flat list of
// (relative_path, contents) pairs generated by service/build.rs from
// docs/src/**/*.md.
//
include!(concat!(env!("OUT_DIR"), "/embedded_docs.rs"));

//
// A single retrievable unit of documentation: one markdown section, keyed by
// its source page and heading trail. Chunking at the heading level keeps each
// unit topically coherent and small enough that a handful can be injected into
// a prompt without dominating the context window.
//

pub struct DocChunk {
    pub path: String,
    pub heading: String,
    pub body: String,
}

//
// Parse all embedded docs into heading-level chunks, once, on first use.
//

fn all_chunks() -> &'static Vec<DocChunk> {
    static CHUNKS: OnceLock<Vec<DocChunk>> = OnceLock::new();
    CHUNKS.get_or_init(|| {
        let mut chunks = Vec::new();
        for (path, content) in EMBEDDED_DOCS {
            chunk_page(path, content, &mut chunks);
        }
        chunks
    })
}

//
// Split one markdown page into chunks at ATX headings (lines beginning with
// `#`). Content before the first heading is attached to a synthetic chunk
// named after the page. Fenced code blocks are tracked so a `#` inside a code
// fence is not mistaken for a heading.
//

fn chunk_page(path: &str, content: &str, out: &mut Vec<DocChunk>) {
    let mut heading = page_title(path);
    let mut body = String::new();
    let mut in_fence = false;

    let flush = |heading: &str, body: &mut String, out: &mut Vec<DocChunk>| {
        if !body.trim().is_empty() {
            out.push(DocChunk {
                path: path.to_string(),
                heading: heading.to_string(),
                body: std::mem::take(body),
            });
        } else {
            body.clear();
        }
    };

    for line in content.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            in_fence = !in_fence;
        }

        if !in_fence && trimmed.starts_with('#') {
            flush(&heading, &mut body, out);
            heading = trimmed.trim_start_matches('#').trim().to_string();
            if heading.is_empty() {
                heading = page_title(path);
            }
        } else {
            body.push_str(line);
            body.push('\n');
        }
    }
    flush(&heading, &mut body, out);
}

//
// Derive a human-ish page title from a doc path, e.g.
// "usage/log-query.md" -> "log query".
//

fn page_title(path: &str) -> String {
    path.trim_end_matches(".md")
        .rsplit('/')
        .next()
        .unwrap_or(path)
        .replace(['-', '_'], " ")
}

//
// Tokenize into lowercase alphanumeric terms, dropping very short tokens and a
// small set of common stopwords that carry no retrieval signal.
//

fn tokenize(text: &str) -> Vec<String> {
    text.split(|c: char| !c.is_alphanumeric())
        .filter_map(|w| {
            let w = w.to_lowercase();
            if w.len() < 3 || STOPWORDS.contains(&w.as_str()) {
                None
            } else {
                Some(w)
            }
        })
        .collect()
}

const STOPWORDS: &[&str] = &[
    "the", "and", "for", "are", "how", "does", "did", "can", "you", "your", "with", "what", "when",
    "where", "why", "who", "that", "this", "from", "into", "was", "were", "will", "would",
    "should", "there", "here", "have", "has", "had", "not", "but", "all", "any", "get", "got",
    "use", "used", "using", "about", "which", "them", "they", "its",
];

//
// Score a chunk against the query terms. Heading matches are weighted more
// heavily than body matches, and the score is length-normalized so short,
// on-topic sections are not out-competed by long tangential ones.
//

fn score_chunk(chunk: &DocChunk, query_terms: &[String]) -> f32 {
    let heading = chunk.heading.to_lowercase();
    let body = chunk.body.to_lowercase();
    let body_len = (chunk.body.split_whitespace().count().max(1)) as f32;

    let mut score = 0.0f32;
    for term in query_terms {
        if heading.contains(term.as_str()) {
            score += 3.0;
        }
        let hits = body.matches(term.as_str()).count() as f32;
        if hits > 0.0 {
            //
            // Sub-linear term frequency (1 + ln tf) so repeated terms help but
            // with diminishing returns, then normalized by section length.
            //
            score += (1.0 + hits.ln()) / body_len.sqrt();
        }
    }
    score
}

//
// Tool-facing search: rank chunks against a free-text query and return a
// compact list of matches (page, heading, snippet) so the assistant can decide
// which pages to read in full.
//

pub fn search(query: &str, top_n: usize) -> String {
    search_chunks(query, top_n, all_chunks())
}

fn search_chunks(query: &str, top_n: usize, chunks: &[DocChunk]) -> String {
    let terms = tokenize(query);
    if terms.is_empty() {
        return "No usable search terms in the query.".to_string();
    }

    let mut scored: Vec<(f32, &DocChunk)> = chunks
        .iter()
        .map(|chunk| (score_chunk(chunk, &terms), chunk))
        .filter(|(score, _)| *score > 0.0)
        .collect();
    scored.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));

    if scored.is_empty() {
        return format!(
            "No documentation sections matched \"{}\". Try different keywords, or read a page \
             from the table of contents with read_doc.",
            query
        );
    }

    let mut out = String::new();
    for (_, chunk) in scored.into_iter().take(top_n) {
        let snippet: String = chunk
            .body
            .split_whitespace()
            .take(28)
            .collect::<Vec<_>>()
            .join(" ");
        out.push_str(&format!(
            "- {} \u{2014} {}\n  {}\n",
            chunk.path.trim_end_matches(".md"),
            chunk.heading,
            snippet
        ));
    }
    out
}

//
// Normalize a model-supplied documentation path for case/format-insensitive
// matching. Slash direction and case must be unified *before* stripping the
// leading "./" and trailing ".md": a Windows-style relative path puts the
// backslash directly after the dot (".\usage\recon.md"), which the "./"
// strip would otherwise miss since it never sees a leading "./" to strip;
// and an uppercase ".MD" would survive a case-sensitive suffix strip
// performed before lowercasing.
//

fn normalize_doc_path(path: &str) -> String {
    path.trim()
        .replace('\\', "/")
        .to_lowercase()
        .trim_start_matches("./")
        .trim_end_matches(".md")
        .to_string()
}

//
// Tool-facing page read: return the full text of a documentation page by path,
// tolerant of a leading "./", a missing ".md", and case. Truncated to
// `max_chars` characters so a single read stays bounded.
//

pub fn read_page(path: &str, max_chars: usize) -> Option<String> {
    read_page_from(path, max_chars, EMBEDDED_DOCS)
}

fn read_page_from(path: &str, max_chars: usize, docs: &[(&str, &str)]) -> Option<String> {
    let want = normalize_doc_path(path);

    docs.iter().find_map(|(p, content)| {
        if normalize_doc_path(p) == want {
            let truncated: String = content.chars().take(max_chars).collect();
            let note = if truncated.len() < content.len() {
                "\n\n[...page truncated...]"
            } else {
                ""
            };
            Some(format!("{}{}", truncated, note))
        } else {
            None
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chunk_page_splits_on_headings_and_ignores_fenced_hashes() {
        let md = "# Real Heading\nbody text\n```\n# not a heading\n```\nmore body\n\
                  ## Sub Heading\nsub body\n";
        let mut out = Vec::new();
        chunk_page("usage/example.md", md, &mut out);

        assert_eq!(out.len(), 2);
        assert_eq!(out[0].heading, "Real Heading");
        assert!(out[0].body.contains("# not a heading"));
        assert!(out[0].body.contains("more body"));
        assert_eq!(out[1].heading, "Sub Heading");
        assert!(out[1].body.contains("sub body"));
    }

    #[test]
    fn chunk_page_attaches_preheading_content_to_the_page_title() {
        let md = "intro text before any heading\n# First Heading\nbody\n";
        let mut out = Vec::new();
        chunk_page("usage/log-query.md", md, &mut out);

        assert_eq!(out[0].heading, "log query");
        assert!(out[0].body.contains("intro text"));
    }

    #[test]
    fn tokenize_drops_stopwords_and_short_terms() {
        assert_eq!(
            tokenize("how do you use the recon node"),
            vec!["recon", "node"]
        );
    }

    #[test]
    fn score_chunk_weights_heading_matches_over_body_matches() {
        let heading_match = DocChunk {
            path: "p".to_string(),
            heading: "recon".to_string(),
            body: "unrelated text".to_string(),
        };
        let body_match = DocChunk {
            path: "p".to_string(),
            heading: "unrelated".to_string(),
            body: "recon".to_string(),
        };
        let terms = vec!["recon".to_string()];

        assert!(score_chunk(&heading_match, &terms) > score_chunk(&body_match, &terms));
    }

    #[test]
    fn page_title_humanizes_the_file_name() {
        assert_eq!(page_title("usage/log-query.md"), "log query");
        assert_eq!(page_title("recon.md"), "recon");
    }

    #[test]
    fn normalize_doc_path_treats_equivalent_spellings_the_same() {
        //
        // ".\usage\recon.md" and "USAGE\RECON.MD" are the two shapes that
        // previously broke: a Windows-style leading ".\" and an uppercase
        // extension, both fixed by reordering slash/case normalization
        // ahead of the "./" and ".md" strips.
        //
        let variants = [
            "usage/recon.md",
            "./usage/recon",
            "USAGE/RECON",
            "usage\\recon",
            ".\\usage\\recon.md",
            "USAGE\\RECON.MD",
        ];

        for variant in variants {
            assert_eq!(normalize_doc_path(variant), "usage/recon");
        }
    }

    #[test]
    fn read_page_from_resolves_path_shape_variants() {
        let docs: &[(&str, &str)] = &[("usage/recon.md", "Recon page contents.")];

        for variant in [".\\usage\\recon.md", "./usage/recon", "USAGE/RECON.MD"] {
            assert_eq!(
                read_page_from(variant, 100, docs).as_deref(),
                Some("Recon page contents.")
            );
        }
    }

    #[test]
    fn read_page_from_truncates_and_notes_it() {
        let docs: &[(&str, &str)] = &[("usage/recon.md", "0123456789")];

        let page = read_page_from("usage/recon", 4, docs).unwrap();

        assert!(page.starts_with("0123"));
        assert!(page.contains("[...page truncated...]"));
    }

    #[test]
    fn read_page_from_returns_none_for_unknown_path() {
        let docs: &[(&str, &str)] = &[("usage/recon.md", "content")];
        assert!(read_page_from("usage/nonexistent", 100, docs).is_none());
    }

    #[test]
    fn search_chunks_ranks_heading_match_first() {
        let chunks = vec![
            DocChunk {
                path: "a.md".to_string(),
                heading: "Unrelated".to_string(),
                body: "recon mentioned once".to_string(),
            },
            DocChunk {
                path: "b.md".to_string(),
                heading: "Recon Operations".to_string(),
                body: "how to run a recon".to_string(),
            },
        ];

        let result = search_chunks("recon", 5, &chunks);

        assert!(result.find("Recon Operations").unwrap() < result.find("Unrelated").unwrap());
    }

    #[test]
    fn search_chunks_reports_no_usable_terms() {
        let result = search_chunks("the a is", 5, &[]);
        assert_eq!(result, "No usable search terms in the query.");
    }
}
